### ISSUE TITLE
Question - compare_subset "ratio"

### ISSUE THREAD

**Issue by amacanovic** [kasperwelbers/tcorpus#2]
Dear Kasper,

First, I'd like to thank you for your work on this package! I found it very intuitive to use and it has been a great tool for analysis!

I have a question about the "ratio" column that is the result of the "compare_subset" function.
I was unable to understand from the documentation - but how is it calculated? Is this the Log Likelihood Ratio? Or a different measure?

Thank you in advance!

**Comment by kasperwelbers** [comment]
Dear @anamuu,

I'm happy to hear that you like the package! 

The compare_subset (and compare corpus functions in general) could indeed use more documentation. The reported ratio is the ratio of the probabilities (or you might say likelihood ratio). It's redundant in the sense that you could simply calculate it yourself as `p.x / p.y`. As the ratio is not log transformed, the interpretation is that a term is (relatively) less common in the subset if the ratio is between 0 and 1, and more common if ratio > 1. 

Note that the reported probabilities are smoothed (Laplace smoothing), so that the ratio is never 0 or Inf. So you can safely log transform it if you prefer. In the plot method for the comparison output we do this to get a more intuitive x-axis (which I'll add to the documentation). 

If you have any alternative measures that you prefer, please let us know.
