### ISSUE TITLE
Feature Request: udpipe parallel computing

### ISSUE THREAD

**Issue by mrwunderbar666** [kasperwelbers/tcorpus#3]
Thanks for the useful tools!

I've seen that udpipe supports parallel computing for the annotation process, which can bring quite reasonable speed ups. See their [documentation](https://cran.r-project.org/web/packages/udpipe/vignettes/udpipe-parallel.html):

`annotation <- udpipe(x, path, parallel.cores = 2)`

Could it be added to this part of the code?

https://github.com/kasperwelbers/corpustools/blob/51354441c04de99a796baa59636cce21707a9a1b/R/udpipe.r#L125

**Comment by kasperwelbers** [comment]
Thanks for the suggestion! I've just now pushed an update that adds the udpipe_cores argument to create_tcorpus. 

I will need to properly test this before I put it on CRAN, especially for windows devices, because I didn't use the udpipe implementation. The reason is that in corpustools we already do the parsing in batches, so that for large jobs we can report progress and keep a cache of completed batches (so that you can easily parse large batches over multiple session, and don't lose progress if R crashes midway). If we used the udpipe argument for parallel.cores, we would only parallelize within these batches, which would require much needless overhead. Instead I therefore parallelized the processing of the batches themselves. 

A quick benchmark shows that this is indeed quite worthwhile:

```
> library(microbenchmark)
> microbenchmark(times = 1,unit = 's',
+   tc1 = create_tcorpus(sotu_texts, doc_col='id', udpipe_model='english-ewt', udpipe_cache = 0, udpipe_cores = 1),
+   tc2 = create_tcorpus(sotu_texts, doc_col='id', udpipe_model='english-ewt', udpipe_cache = 0, udpipe_cores = 8)
+ )
 
Unit: seconds
 expr       min        lq      mean    median        uq       max neval
  tc1 27.784910 27.784910 27.784910 27.784910 27.784910 27.784910     1
  tc2  5.732637  5.732637  5.732637  5.732637  5.732637  5.732637     1
```

About a 5 times speed up for using 8 cores instead of 1.

**Comment by mrwunderbar666** [comment]
Thanks!

I am also gonna test it over the coming days on my machines (Windows & Linux) and will report back

**Comment by kasperwelbers** [comment]
That would be great, thanks!

**Comment by mrwunderbar666** [comment]
Just tested it here on my Windows 10 desktop system (i5-3470, 4 cores, 8GB RAM)

```
> microbenchmark(times = 1,unit = 's',
+                tc1 = create_tcorpus(sotu_texts, doc_col='id', udpipe_model='english-ewt', udpipe_cache = 0, udpipe_cores = 1),
+                tc2 = create_tcorpus(sotu_texts, doc_col='id', udpipe_model='english-ewt', udpipe_cache = 0, udpipe_cores = 4)
+                )

  |++++++++++++++++++++++++++++++++++++++++++++++++++| 100%
  |++++++++++++++++++++++++++++++++++++++++++++++++++| 100%

Unit: seconds
 expr      min       lq     mean   median       uq      max neval
  tc1 47.79613 47.79613 47.79613 47.79613 47.79613 47.79613     1
  tc2 29.37697 29.37697 29.37697 29.37697 29.37697 29.37697     1
```

Works! And is now twice as fast.

Machine information:

```
> Sys.info()
       sysname        release        version       nodename        machine
     "Windows"       "10 x64"  "build 17763" "AXXXX-XXXXX"       "x86-64"
```

**Comment by kasperwelbers** [comment]
Nice, thanks! Since it appears to work, and it is optionally anyway, I'll consider the issue solved and include the update in the next CRAN release. 

Related to this, I've also added the udpipe_batchsize argument to create tcorpus. The default of 50 articles is arbitrary, and especially for very smaller texts (e.g. tweets) the costs of the overhead for using batches might be a bit much. I've set it up so that if the number of texts divided by the number of cores is smaller than the given batchsize, the batchsize is adjusted to evenly distribute texts over the cores. 

If you are not interested in progress bars and caching, you can also set batchsize to Inf so that texts are always evenly distributed over cores (I think this is also the default behavior for udpipe's parallel cores option). For example, for the sotu data using 2 cores this gives a (minor) speed up.

```
microbenchmark(times = 1,unit = 's',
  tc1 = create_tcorpus(sotu_texts, doc_col='id', udpipe_model='english-ewt', udpipe_cache = 0, udpipe_cores = 1),
  tc2 = create_tcorpus(sotu_texts, doc_col='id', udpipe_model='english-ewt', udpipe_cache = 0, udpipe_cores = 2),
  tc3 = create_tcorpus(sotu_texts, doc_col='id', udpipe_model='english-ewt', udpipe_cache = 0, udpipe_cores = 2, udpipe_batchsize=Inf)
)
Unit: seconds
 expr      min       lq     mean   median       uq      max neval
  tc1 38.90891 38.90891 38.90891 38.90891 38.90891 38.90891     1
  tc2 24.36979 24.36979 24.36979 24.36979 24.36979 24.36979     1
  tc3 20.51399 20.51399 20.51399 20.51399 20.51399 20.51399     1
```
