### ISSUE TITLE
search_dictionary(): using '+' as separator

### ISSUE THREAD

**Issue by mrwunderbar666** [kasperwelbers/tcorpus#4]
corpustools version 0.4.9 (CRAN)

This may seem trivial, but using a dictionary that uses `+` to separate multi-word strings is a bit a hazzle and causes bugs.

The documentation reads as follows:

> A regular expression for separating multi-word lookup strings (default is " ", which is what quanteda dictionaries use). For example, if the dictionary contains "Barack Obama", sep should be " " so that it matches the consequtive tokens "Barack" and "Obama". In some dictionaries, however, it might say "Barack+Obama", so in that case sep = '\\+' should be used.

Trying this causes errors:

```
library(corpustools)
tc = create_tcorpus(sotu_texts, doc_column = 'id', text_columns = 'text', split_sentences=T)
dict <- data.frame(code = rep('USA', 2), keyword = c('United+States', 'USA'))
hits <- search_dictionary(tc, dict, token_col = 'token', string_col = 'keyword', sep = '\+')
# Error: '\+' is an unrecognized escape in character string starting "'\+"

hits <- search_dictionary(tc, dict, token_col = 'token', string_col = 'keyword', sep = '+')
# Error in stri_split_regex(str, regex, ...) : 
#  Syntax error in regex pattern. (U_REGEX_RULE_SYNTAX, context=`+`)

hits <- search_dictionary(tc, dict, token_col = 'token', string_col = 'keyword', sep = '\\+')
# Gives wrong matches (does not match 'United States')

dict <- data.frame(code = rep('USA', 2), keyword = c('United States', 'USA'))
hits <- search_dictionary(tc, dict, token_col = 'token', string_col = 'keyword')
# Works as expected
```

I am not sure how to approach this, but I think this could be a roadblock for new users.

**Comment by kasperwelbers** [comment]
Hi @mrwunderbar666,

Thanks for pointing this one out! There was actually a bug that at some point creeped in here. The stupid thing is that the unit test did not cover a regex symbol that needed to be escaped, so it didn't catch it. 

It should now be working again, and it's about time that I push the minor changes of the past months to CRAN anyway. I'll probably do so tomorrow if I find time to test some more. 

95d37de91e7e00ff2b843804a9255a100156be77

Also, the '\+' in the documentation was actually a mistake, ironically due to escaping. In my docstring I wrote '\\x', but then markdown turns this into '\x'. So now the docstring has the beautiful '\\\\x' so that the documentation actually shows \\x.

Best,
Kasper
