### ISSUE TITLE
Unable to setup context-level "sentence" when attempting to make semnet_window()

### ISSUE THREAD

**Issue by enduros7723** [kasperwelbers/tcorpus#6]
Hello!
I tried to build up a semantic network using the `semnet_window()` function, based on a small portion of sentences and adding an argument `context_level = "sentence"`. Unfortunately, the process fails, as it provides the message:

```
Error in `[.data.table`(self$tokens, , columns, with = F) :
  column(s) not found: token_i
```

In order to reproduce please find an example attached below:
```{r}
library(corpustools)
test <- create_tcorpus("Lorem ipsum dolor sit amet consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa.", split_sentences=T)
test$tokens
semnet_window(test, feature = "token", context_level = "sentence", window.size = 3)
```

---

Some technical information:
* R: 4.0.5
* OS: GNU/Linux
* corpustools_0.4.10

**Comment by kasperwelbers** [comment]
Hi @enduros7723,

Thanks for the heads up! I fixed the bug, so if you install the dev version from github it should work.

I'll try to push it to CRAN soon, but there is some big refactor due to an update of the Matrix package that I need to take care of first.

Closing this issue for now, but feel free to re-open if I missed anything
